"""Modife de produit

Revision ID: 0a61f54cf67b
Revises: 337422143838
Create Date: 2025-02-13 00:08:24.030621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a61f54cf67b'
down_revision = '337422143838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('categorie',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=225),
               existing_nullable=True)

    # ### end Alembic commands ###
