"""Ajout de photo

Revision ID: 337422143838
Revises: 
Create Date: 2025-02-06 14:21:15.258269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337422143838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
